In [2]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5, 6, 7])
print(my_array)

[1 2 3 4 5 6 7]


In [6]:
import pandas as pd

meu_df = pd.DataFrame({'teste': [23,21,1],
                       'teste 2': [1,8,9]
                       })
meu_df

teste  teste 2
0     23        1
1     21        8
2      1        9

In [9]:
pd.Series(my_array)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [14]:
import numpy as np

array_numpy = np.random.randint(0, 100, size=(10))

print(array_numpy)
print(array_numpy.dtype)

[87 49 59 17 22  2 82 91 70 27]
int32


In [17]:
import numpy as np

array = np.random.rand(5, 5)
print(array)

min_value = np.min(array)
max_value = np.max(array)
mean_value = np.mean(array)

print("O valor mínimo da matriz é:", min_value)
print("O valor máximo da matriz é:", max_value)
print("A média da matriz é:", mean_value)


[[0.22035084 0.37780354 0.10726259 0.70168622 0.04238417]
 [0.26222484 0.92591003 0.99086122 0.75635247 0.0519909 ]
 [0.8654453  0.03510329 0.49867106 0.84833834 0.04083422]
 [0.45742838 0.08010363 0.15314472 0.13434149 0.36526346]
 [0.42469054 0.38198958 0.10037069 0.92785817 0.55015867]]
O valor mínimo da matriz é: 0.03510329157798464
O valor máximo da matriz é: 0.9908612196983303
A média da matriz é: 0.412022734909151


In [19]:
import numpy as np

array = np.random.rand(10)
print(array)

array_multiplicado = array * 10

array_inteiro = array_multiplicado.astype('int32')

print(array_inteiro)


[0.01443225 0.45968729 0.18895533 0.00623846 0.00116362 0.6954167
 0.07581678 0.84965693 0.3484174  0.88585067]
[0 4 1 0 0 6 0 8 3 8]


In [22]:
import numpy as np

array = np.random.randint(0, 10, size=(3, 3))
print(array)

array[1] = -1
print(array)

[[6 0 3]
 [2 7 3]
 [1 2 5]]
[[ 6  0  3]
 [-1 -1 -1]
 [ 1  2  5]]


In [23]:
import pandas as pd

df = pd.DataFrame({
    'fruta': ['Banana', 'Maça', 'Pera'],
    'preco': [7.90, 10.20, 11.80],
    'quantidade': [12, 3, 4]
})

print(df)

    fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4
